/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under BSD 3-Clause license,
  * the "License"; You may not use this file except in compliance with the
  * License. You may obtain a copy of the License at:
  *                        opensource.org/licenses/BSD-3-Clause
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "dma.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "Logic_layer.h"
#include "API_func.h"
#include "stm32_ub_vga_screen.h"
#include <string.h>

/* One byte buffer for interrupt reception */
uint8_t rx;

/* UART handle (generated by CubeMX) */
extern UART_HandleTypeDef huart2;

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */
input_vars input;

volatile char container[1024];
volatile int temp;
volatile int key;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */


  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_TIM1_Init();
  MX_TIM2_Init();
  MX_USART2_UART_Init();
  /* USER CODE BEGIN 2 */

  char msg[] = "STM32 UART ready!\r\n";
  HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);


  UB_VGA_Screen_Init(); // Init VGA-Screen

  int i;

  for(i = 0; i < LINE_BUFLEN; i++)
	  input.line_rx_buffer[i] = 0;

  // Reset some stuff
  input.byte_buffer_rx[0] = 0;
  input.char_counter = 0;
  input.command_execute_flag = FALSE;

  // HAl wants a memory location to store the charachter it receives from the UART
  // We will pass it an array, but we will not use it. We declare our own variable in the interupt handler
  // See stm32f4xx_it.c
  HAL_UART_Receive_IT(&huart2, input.byte_buffer_rx, BYTE_BUFLEN);

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  API_clearscreen(VGA_COL_BLACK);
  HAL_Delay(3000);
  for(int i = 10; i < 240; i++)
  {
    API_draw_line(1, i, 319, i, i, 1, 0);
  }
  API_draw_bitmap(130, 90, 1);

  HAL_Delay(1000);

  API_clearscreen(VGA_COL_WHITE);
 
  HAL_Delay(100);

  while (1)
  {

    // Check if we have a complete line to process
    if (input.command_execute_flag == TRUE) {
      // Echo back the received line
      HAL_UART_Transmit(&huart2, (uint8_t*)input.line_rx_buffer, input.char_counter, HAL_MAX_DELAY);
      HAL_UART_Transmit(&huart2, (uint8_t*)"\r\n", 2, HAL_MAX_DELAY);
      
      struct LogicInterface cmd = {0};
      memset(&cmd, 0, sizeof(cmd));

      uint32_t kommando = 0;
      uint32_t strnglgth = 0;

      for (int j = 0; j < input.msglen+1; j++)
      {
    	if(input.line_rx_buffer[j] == '\0')
    	{
    		strnglgth = j;
    	}
      }
      for(int j = 0; j < input.msglen; j++)
      {
    	if(input.line_rx_buffer[j] == ',')
    	{
    		kommando = j-1;
    		for(int i = 0; i <= kommando; i++)
    		{
    			cmd.function_name[i] = input.line_rx_buffer[i];
    		}

    		break;
    	}
      }

      cmd.argument_len = strnglgth - kommando;
      char arg[128]= {0};
      for(int j = 0; j<= input.msglen-kommando;j++)
      {
    	  arg[j] = input.line_rx_buffer[j+kommando+2];
      }

      cmd.arguments = &arg;
      execute_command(&cmd);
      
      // Reset for next command
      input.char_counter = 0;
      input.command_execute_flag = FALSE;
      memset((void*)input.line_rx_buffer, 0, LINE_BUFLEN);
    }

    HAL_Delay(100);
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 4;
  RCC_OscInitStruct.PLL.PLLN = 168;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */
uint8_t rxChar;
char uartBuffer[128];
uint16_t uartIndex = 0;

/**
  * @brief  Reads a string from UART and sends it back
  * @param  huart: UART handle
  * @param  buffer: Pointer to buffer to store received string
  * @param  maxLen: Maximum length of string to receive
  * @retval Number of characters received
  */
uint16_t UART_ReadStringEcho(UART_HandleTypeDef *huart, char *buffer, uint16_t maxLen)
{
  uint16_t index = 0;
  uint8_t rxChar;
  
  while (index < maxLen - 1) {
    // Read one character from UART
    if (HAL_UART_Receive(huart, &rxChar, 1, HAL_MAX_DELAY) == HAL_OK) {
      buffer[index] = rxChar;
      
      // Echo back the character
      HAL_UART_Transmit(huart, &rxChar, 1, HAL_MAX_DELAY);
      
      // Check for string terminator (newline or carriage return)
      if (rxChar == '\n' || rxChar == '\r') {
        buffer[index] = '\0';  // Null-terminate the string
        return index;
      }
      index++;
    } else {
      break;  // Error occurred
    }
  }
  
  buffer[index] = '\0';  // Null-terminate the string
  return index;
}



#ifdef __GNUC__
	#define USART_PRINTF int __io_putchar(int ch)		//With GCC/RAISONANCE printf calls __io_putchar()
#else
	#define USART_PRINTF int fputc(int ch, FILE *f)		//With other compiler printf calls fputc()
#endif /* __GNUC__ */

//Retargets the C library printf function to the USART
USART_PRINTF
{
	HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1, 0xFFFF);	//Write character to UART2
	return ch;												//Return the character
}

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */

  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     tex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
